PD2-2177: created GMAT recruiter landing project
mindojo/gmat-recruiter-landing pull request #1
Opened 2020-09-16 12:43 UTC by alexp374

https://mindojo.atlassian.net/browse/PD2-2177

js mostly taken from platformized landing: 
* utils/bootstrap-custom.js  
* utils/cookie-consent.js (will be updated)         
* utils/dynamic-nav.js 
* utils/mobile-check.js    
* utils/sentry.js   
* utils/tracking.js (will be updated)         
* utils/carousel.js          
* utils/cookie-management.js  
* utils/fetch-config.js (will be updated) 
* utils/tooltip.js  
* utils/utils.js

![screenshot-localhost_4211-2020 09 16-15_36_17](https://user-images.githubusercontent.com/60871893/93338098-a6e06b00-f832-11ea-916a-f132d6de73d5.png)
![screenshot-localhost_4211-2020 09 16-15_36_01](https://user-images.githubusercontent.com/60871893/93338100-a7790180-f832-11ea-8625-d24f6e745531.png)

2020-09-16 12:45 UTC, alexp374 commented on src/scripts/utils/config.json
> +{
this is just an example config, while we have no BS on the backend. will be in gitignore in future

2020-09-21 11:10 UTC, kundojo commented on prepare.js
> +const host = process.env.ENVIRONMENT == "development" ? 'https://blp.dev.mndj.link/' : 'http://bloombergprep.com/';
i see there an obvious problem - you cant run this for stage or any other domain. why dont do location.host?

2020-09-21 11:10 UTC, kundojo commented on recruiter.nginx.conf
> +server {
recruiter.dev.nginx.conf please. recruiter.nginx.conf for prod

2020-09-21 11:11 UTC, kundojo commented on prepare.js
> +const host = process.env.ENVIRONMENT == "development" ? 'https://blp.dev.mndj.link/' : 'http://bloombergprep.com/';
oh sorry i see this script is run before, during the build.. idk how to solve the problem

2020-09-21 11:13 UTC, kundojo commented on src/index.hbs
> +<div class="sections-container" style="background-image: url({{config.signupConfig.infoPanel.bg}})">
config is not obligatory uses infoPanel - you should implement the same logic as in core. if infoPanel.isEnabled - draw a section we primary color as bg. Otherwise - place form directly in the center

2020-09-21 11:14 UTC, kundojo commented on src/scripts/components/signup-modal/component.js
> +    const tosLabel = `I agree to the
this string exists fully in [signupConfig](https://github.com/mindojo/Brain2/blob/develop/scripts/update_front_config/bloombergprep/base/base.json#L14)

2020-09-21 11:16 UTC, kundojo commented on src/scripts/components/signup-modal/partials/radio.hbs
> +  <label class="ui-checkbox ui-radio">
why cant u use components from ui-kit? you can grab only view of them for build

2020-09-21 11:18 UTC, kundojo commented on src/scripts/components/signup-modal/template.hbs
> +          <p>Occasionally we'd like to inform you of exclusive offers and give you personalized coupons by email. We'll treat your personal details with care.</p>
all this texts exist in config but in [core](https://github.com/mindojo/mindojo-core/blob/ui-kit-new/config/configs/signup-config.js#L2) - we have to move them to front config

2020-09-21 11:19 UTC, kundojo commented on src/scripts/components/signup-modal/utils.js
> +        other_data: data,
https://github.com/mindojo/mindojo-core/blob/ui-kit-new/addon/modules/signup/controller.js#L287
`has_accepted_service_messages: true,`

2020-09-21 11:19 UTC, kundojo commented on src/scripts/utils/carousel.js
> +  } else {
else to the next lint

2020-09-21 11:21 UTC, kundojo commented on src/scripts/utils/config.json
> +{
but you dont fetch it from BS any way - you fetch it from apps/api/config why you cant do it now?

2020-09-21 11:22 UTC, kundojo commented on src/scripts/utils/config.json
> +      "button-secondary-inverted": "#7290fb"
deprecated vars

2020-09-21 11:22 UTC, kundojo commented on src/scripts/utils/config.json
> +      "palette-p1-700": "#4465D9",
also i would strongly recommend you to inject skin_vars into ::root and use skin vars in styles

2020-09-21 11:23 UTC, kundojo commented on src/scripts/utils/cookie-management.js
> +};
please check the new implementation in landings  https://github.com/mindojo/platformized-landings/pull/24

2020-09-21 11:24 UTC, kundojo commented on src/scripts/utils/fetch-config.js
> +// TODO: https://mindojo.atlassian.net/browse/PD2-2193 update the config afterfetch
u just copy pasted the whole file from landing with todo? :)

2020-09-21 11:25 UTC, kundojo commented on src/scripts/utils/fetch-config.js
> +  return new Promise(function(resolve, reject) {
please discuss with ab redirection users with old browsers to "unsupported" page https://github.com/mindojo/mindojo-core/blob/ui-kit-new/inline/mindojo-cache.js#L49

2020-09-21 11:25 UTC, kundojo commented on src/scripts/utils/fetch-config.js
> +      // in any case we can return prefeted config
return prefetched

2020-09-21 11:27 UTC, kundojo commented on src/scripts/utils/fetch-config.js
> +};
duplicates with utils. please dont do duplicates in any cost

2020-09-21 11:27 UTC, kundojo commented on src/scripts/utils/fetch-config.js
> +    ...config.products[0],
why products[0] ? there will be a lot of products

2020-09-21 11:28 UTC, kundojo commented on src/scripts/utils/sentry.js
> +  scr.src = 'https://cdn.ravenjs.com/3.16.1/raven.min.js';
raven is deprecated btw

2020-09-21 11:29 UTC, kundojo commented on src/styles/base/components/button.sass
> +  background-color: ui-ref("colors", scheme-inverted-700)
scheme-inverted-700 is deprecated, check what vars is used now in uikit

2020-09-21 11:29 UTC, kundojo commented on src/styles/base/components/button.sass
> +  color: $white
should be var as well

2020-09-21 11:30 UTC, kundojo commented on src/styles/base/components/carousel.sass
> +    color: ui-ref("colors", scheme-inverted-700)
scheme-inverted-700 is deprecated. border-color should be var as well

2020-09-21 11:31 UTC, kundojo commented on src/styles/base/components/inputs.sass
> +  color: ui-ref("colors", text)
can we use the same names as used for uikit please?

2020-09-21 11:31 UTC, kundojo commented on src/styles/base/components/inputs.sass
> +    color: ui-ref("colors", palette-s1-600)
can we please use all refs the same as used in uikit?

2020-09-21 11:31 UTC, kundojo commented on src/styles/base/components/inputs.sass
> +.ui-checkbox
why we cant use ui-checkbox from uikit?

2020-09-21 11:33 UTC, alexp374 commented on src/styles/base/components/inputs.sass
> +    color: ui-ref("colors", palette-s1-600)
they aren't?

2020-09-21 11:50 UTC, alexp374 commented on src/scripts/utils/fetch-config.js
> +    ...config.products[0],
it is just for testing. I have yet no clue how it will be deployed. we have a task for configuration the config, and I have TODO here

2020-09-21 11:50 UTC, alexp374 commented on src/scripts/utils/fetch-config.js
> +};
forgot to remove, tnx

2020-09-21 11:51 UTC, alexp374 commented on src/scripts/utils/fetch-config.js
> +// TODO: https://mindojo.atlassian.net/browse/PD2-2193 update the config afterfetch
kinda

2020-09-21 11:54 UTC, alexp374 commented on src/scripts/utils/config.json
> +{
I assume BS will have a slightly different config then we have for the app now

2020-09-21 11:55 UTC, alexp374 commented on prepare.js
> +const host = process.env.ENVIRONMENT == "development" ? 'https://blp.dev.mndj.link/' : 'http://bloombergprep.com/';
Depends on how we will deploy the BS back. I think we will pass the env var to the script

2020-09-21 12:39 UTC, alexp374 commented on src/scripts/components/signup-modal/partials/radio.hbs
> +  <label class="ui-checkbox ui-radio">
They are huge, and aren't support a full customization yet

2020-09-21 12:43 UTC, alexp374 commented on src/scripts/components/signup-modal/utils.js
> +        other_data: data,
BS has a different API https://github.com/mindojo/Brain2/blob/develop/brain/api/bschools.py#L31. Besides that is just a draft, signup it a different task

2020-09-21 12:49 UTC, alexp374 commented on src/scripts/utils/config.json
> +      "palette-p1-700": "#4465D9",
I did inject them into the body

2020-09-21 12:50 UTC, alexp374 commented on src/scripts/utils/fetch-config.js
> +  return new Promise(function(resolve, reject) {
That is a landing. I don't think it is needed here

2020-09-21 12:50 UTC, alexp374 commented on src/scripts/utils/fetch-config.js
> +  return new Promise(function(resolve, reject) {
But I will

2020-09-21 13:03 UTC, alexp374 commented on src/styles/base/components/inputs.sass
> +.ui-checkbox
unfortunately, it isn't customizable enough

2020-09-21 13:20 UTC, kundojo commented on src/scripts/utils/config.json
> +{
i think it is you who should create front configs, not vic. 
i think you have to send window.location in request, because we will use such scheme for multiproduct configs

2020-09-21 13:21 UTC, kundojo commented on src/scripts/components/signup-modal/utils.js
> +        other_data: data,
has_accepted_service_messages should be true anyway. please ask ab

2020-09-21 13:22 UTC, kundojo commented on src/scripts/utils/fetch-config.js
> +  return new Promise(function(resolve, reject) {
not all browsers support promise we will have trash in sentry. but please discuss with ab first

2020-09-22 06:29 UTC, kundojo requested changes

2020-09-22 06:29 UTC, kundojo commented on src/scripts/utils/fetch-config.js
> +// TODO: https://mindojo.atlassian.net/browse/PD2-2193 update the config afterfetch
U need to create configs with 'hult' environment, send "environment:hult" in request and adjust front config api code

2020-09-22 06:29 UTC, kundojo commented on src/scripts/components/signup-modal/template.hbs
> +            class="btn signup-linkedin-btn btn-block"
Any todo to implement LinkedIn signup?

2020-09-22 06:29 UTC, kundojo commented on src/styles/base/main.sass
> +  color: ui-ref("colors", scheme-inverted-700)
Don't use schemeinverted. In general would be good do not use palette in sass

2020-09-22 06:29 UTC, kundojo commented on src/styles/base/sections/plans-tired.sass
> +          border-right: solid 1px ui-ref("colors", palette-s1-400)
Do not use palette in sass

2020-09-22 06:29 UTC, kundojo commented on src/styles/utilities/ui-helpers.scss
> +@function ui-map($name: null, $values: ()) {
U have unkit now why to copy paste?

2020-09-22 06:29 UTC, kundojo commented on src/templates/partials/footer.hbs
> +          GMAT® is a registered trademark of the Graduate Management Admission Council™.
Should be in config

2020-09-22 06:29 UTC, kundojo commented on src/templates/partials/theme-styles.hbs
> +      --colors-intro-bg: url({{config.signupConfig.infoPanel.introBg}})
Why intro bg is in vars but not bg that u use in index?

2020-09-22 06:29 UTC, kundojo commented on src/templates/sections/plans/tired.hbs
> +                Our Micro Test consists of 5 Quantitative (Math) questions and 5 Verbal (English) questions.
Should be in config as well as number of questions

2020-09-22 08:03 UTC, alexp374 commented on src/scripts/utils/config.json
> +{
I will, you right. But I we don't yet know how exactly should it look like because we have no app

2020-09-22 08:03 UTC, alexp374 commented on src/scripts/utils/config.json
> +{
I have a task for it

2020-09-22 08:06 UTC, alexp374 commented on src/index.hbs
> +<div class="sections-container" style="background-image: url({{config.signupConfig.infoPanel.bg}})">
By design we ever use image on first section or on a whole page, so right now adding another setting will be just unnecessarily increase in size. Anyway binding the landing with config is a different task

2020-09-22 08:07 UTC, alexp374 commented on src/scripts/components/signup-modal/utils.js
> +        other_data: data,
why should we send data which whouldn't be used?

2020-09-22 08:08 UTC, alexp374 commented on src/scripts/utils/config.json
> +      "button-secondary-inverted": "#7290fb"
for now colors are taken from the ui-kit

2020-09-22 08:08 UTC, alexp374 commented on src/scripts/utils/cookie-management.js
> +};
removed for now

2020-09-22 08:09 UTC, alexp374 commented on src/styles/base/components/button.sass
> +  background-color: ui-ref("colors", scheme-inverted-700)
for now colors are taken from the ui-kit

2020-09-22 08:20 UTC, alexp374 commented on src/styles/base/main.sass
> +  color: ui-ref("colors", scheme-inverted-700)
missed that one

2020-09-22 08:20 UTC, alexp374 commented on src/scripts/components/signup-modal/template.hbs
> +            class="btn signup-linkedin-btn btn-block"
we have one

2020-09-22 08:23 UTC, alexp374 commented on src/styles/utilities/ui-helpers.scss
> +@function ui-map($name: null, $values: ()) {
it isn't compiling with the landing environment for some reason

2020-09-22 08:25 UTC, alexp374 commented on src/templates/partials/footer.hbs
> +          GMAT® is a registered trademark of the Graduate Management Admission Council™.
It present in all the templates. Also considering the fact that this is GMAT recruiter, having a legal info is essential for the page. Putting that into the config will be just additional unnecessary payload

2020-09-22 08:26 UTC, alexp374 commented on src/templates/partials/theme-styles.hbs
> +      --colors-intro-bg: url({{config.signupConfig.infoPanel.introBg}})
because it can be different

2020-09-22 08:32 UTC, alexp374 commented on src/templates/sections/plans/tired.hbs
> +                Our Micro Test consists of 5 Quantitative (Math) questions and 5 Verbal (English) questions.
We have a fixed number of questions (at least for now) for ALL the instances of GMAT recruiter. In fact all the apps will use the same exam, so putting number of questions in the config seems completely unnecessary. 
Regarding the plans customization, it is configurable by applying the different partial. I don't think we yet need to put the texts in the config because if we wanted to make every single text for every partial configurable, that will be infinite list of options. We have a task for binding the config so if we need to make it configurable it will be done there.

2020-09-22 08:33 UTC, alexp374 commented on src/styles/base/components/inputs.sass
> +    color: ui-ref("colors", palette-s1-600)
updated

2020-09-22 10:12 UTC, kundojo commented on src/scripts/components/signup-modal/utils.js
> +        other_data: data,
Because user must have this field.

2020-09-22 10:13 UTC, kundojo approved these changes

2020-09-22 10:15 UTC, kundojo commented on src/templates/partials/theme-styles.hbs
> +      --colors-intro-bg: url({{config.signupConfig.infoPanel.introBg}})
I understand - why don't put them both in css vars?

2020-09-22 10:17 UTC, kundojo commented on src/templates/partials/footer.hbs
> +          GMAT® is a registered trademark of the Graduate Management Admission Council™.
And what? I would understand the problem if it would wait api response for render. But u do not wait

2020-09-22 10:18 UTC, kundojo commented on src/styles/utilities/ui-helpers.scss
> +@function ui-map($name: null, $values: ()) {
I think copy pasting is the problem. Show me the error in dm

2020-09-22 10:20 UTC, kundojo commented on src/templates/sections/plans/tired.hbs
> +                Our Micro Test consists of 5 Quantitative (Math) questions and 5 Verbal (English) questions.
Numbers should be in config. Because u have this numbers and estimate duration in both - back and front. Should be on back only and probably even added to front config from another source. Or vv.

2020-09-22 15:30 UTC, kundojo commented on src/scripts/utils/config.json
> +      "socialShareEnabled": 0,
isSocialShareEnabled

2020-09-24 12:33 UTC, merged